### ISSUE TITLE
CHORE - 커넥션 풀 모듈별 설정 최적화 작업

### ISSUE THREAD

**Issue by ongsttt52** [Kernel360/KDEV4-TRACKY-BE#345]
## 어떤 기능인가요?

HikariCP 설정을 모든 모듈이 공통 설정으로 사용하고 있었는데, DB를 전혀 사용하지 않거나 미미하게 사용하는 모듈도 idleConnection을 10개씩 생성해두어서 Too many connections 등의 문제가 발생할 수 있는 상황입니다.

따라서 모듈별로 HikariCP 설정을 분리하는 작업을 진행할 예정입니다.

아래는 현재 생각중인 설정이며 테스트를 통해 적절한 설정을 찾아야 합니다.

## 참고할만한 자료(선택)
```yaml
    # hub
    hikari:
      pool-name: HubHikariCP
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 5000
      idle-timeout: 300000
      max-lifetime: 600000
      leak-detection-threshold: 10000


    # consumer
    hikari:
      pool-name: ConsumerHikariCP
      maximum-pool-size: 20
      minimum-idle: 20
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 1000000
      leak-detection-threshold: 10000


    # web
    hikari:
      pool-name: WebHikariCP
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 10000
      idle-timeout: 300000
      max-lifetime: 600000
      leak-detection-threshold: 10000
```
